### ISSUE TITLE
Audit logs filling up - config change?

### ISSUE THREAD

**Issue by jayaich** [microsoft/OMS-Auditd-Plugin#30]
We have noticed that the '/var/log/audit' log files have been filling up very quickly. Typically 5 log files filled within about 12 hours (each at 20MB, changed from the default 8MB). This means we may well lose information (I'm thinking AVC denials here) overnight or especially at weekends. Usually we have about half a log file (4MB) per day, allowing us enough time to check any denials.

We have also noticed that when running 'systemctl status auoms' that it shows a message every second:

==========
auoms.service - OMS Audit data collection daemon
   Loaded: loaded (/opt/microsoft/auoms/auoms.service; enabled; vendor preset: disabled)
   Active: active (running) since Tue 2019-06-18 21:30:45 BST; 2 days ago
     Docs: man:auoms(8)
 Main PID: 86728 (auoms)
   CGroup: /system.slice/auoms.service
           └─86728 /opt/microsoft/auoms/bin/auoms

Jun 21 15:59:58 cent-5-506 auoms[86728]: AuditRulesMonitor: Found desired audit rules not currently loaded, loading new rules
Jun 21 15:59:59 cent-5-506 auoms[86728]: AuditRulesMonitor: Found desired audit rules not currently loaded, loading new rules
Jun 21 16:00:00 cent-5-506 auoms[86728]: AuditRulesMonitor: Found desired audit rules not currently loaded, loading new rules
Jun 21 16:00:01 cent-5-506 auoms[86728]: AuditRulesMonitor: Found desired audit rules not currently loaded, loading new rules
Jun 21 16:00:02 cent-5-506 auoms[86728]: AuditRulesMonitor: Found desired audit rules not currently loaded, loading new rules
Jun 21 16:00:03 cent-5-506 auoms[86728]: AuditRulesMonitor: Found desired audit rules not currently loaded, loading new rules
Jun 21 16:00:04 cent-5-506 auoms[86728]: AuditRulesMonitor: Found desired audit rules not currently loaded, loading new rules
Jun 21 16:00:06 cent-5-506 auoms[86728]: AuditRulesMonitor: Found desired audit rules not currently loaded, loading new rules
==========

In the audit log files what we see, seemingly every second or so again, is:

=====================
type=CONFIG_CHANGE msg=audit(1561129167.206:26068221): auid=4294967295 ses=4294967295 subj=system_u:system_r:initrc_t:s0 op=remove_rule key=61756F6D73016B65726E656C6D6F64756C6573 list=4 res=1
type=CONFIG_CHANGE msg=audit(1561129167.206:26068222): auid=4294967295 ses=4294967295 subj=system_u:system_r:initrc_t:s0 op=remove_rule key=617564697474616D706572696E670161756F6D73 list=4 res=1
type=CONFIG_CHANGE msg=audit(1561129167.206:26068223): auid=4294967295 ses=4294967295 subj=system_u:system_r:initrc_t:s0 op=remove_rule key=617564697474616D706572696E670161756F6D73 list=4 res=1
type=CONFIG_CHANGE msg=audit(1561129167.206:26068224): auid=4294967295 ses=4294967295 subj=system_u:system_r:initrc_t:s0 op=remove_rule key=61756F6D73017573657267726F7570 list=4 res=1
type=CONFIG_CHANGE msg=audit(1561129167.206:26068225): auid=4294967295 ses=4294967295 subj=system_u:system_r:initrc_t:s0 op=remove_rule key=61756F6D73017573657267726F7570 list=4 res=1
type=CONFIG_CHANGE msg=audit(1561129167.206:26068226): auid=4294967295 ses=4294967295 subj=system_u:system_r:initrc_t:s0 op=remove_rule key=61756F6D730170616D list=4 res=1
type=CONFIG_CHANGE msg=audit(1561129167.206:26068227): auid=4294967295 ses=4294967295 subj=system_u:system_r:initrc_t:s0 op=remove_rule key="auoms" list=4 res=1
type=CONFIG_CHANGE msg=audit(1561129167.206:26068228): auid=4294967295 ses=4294967295 subj=system_u:system_r:initrc_t:s0 op=remove_rule key="auoms" list=4 res=1
type=CONFIG_CHANGE msg=audit(1561129167.207:26068229): auid=4294967295 ses=4294967295 subj=system_u:system_r:initrc_t:s0 op=add_rule key=61756F6D73016B65726E656C6D6F64756C6573 list=4 res=1
type=CONFIG_CHANGE msg=audit(1561129167.211:26068230): auid=4294967295 ses=4294967295 subj=system_u:system_r:initrc_t:s0 op=add_rule key=617564697474616D706572696E670161756F6D73 list=4 res=1
type=CONFIG_CHANGE msg=audit(1561129167.215:26068231): auid=4294967295 ses=4294967295 subj=system_u:system_r:initrc_t:s0 op=add_rule key=617564697474616D706572696E670161756F6D73 list=4 res=1
type=CONFIG_CHANGE msg=audit(1561129167.215:26068232): auid=4294967295 ses=4294967295 subj=system_u:system_r:initrc_t:s0 op=add_rule key=61756F6D73017573657267726F7570 list=4 res=1
type=CONFIG_CHANGE msg=audit(1561129167.215:26068233): auid=4294967295 ses=4294967295 subj=system_u:system_r:initrc_t:s0 op=add_rule key=61756F6D73017573657267726F7570 list=4 res=1
type=CONFIG_CHANGE msg=audit(1561129167.220:26068234): auid=4294967295 ses=4294967295 subj=system_u:system_r:initrc_t:s0 op=add_rule key=61756F6D730170616D list=4 res=1
type=CONFIG_CHANGE msg=audit(1561129167.220:26068235): auid=4294967295 ses=4294967295 subj=system_u:system_r:initrc_t:s0 op=add_rule key="auoms" list=4 res=1
type=CONFIG_CHANGE msg=audit(1561129167.220:26068236): auid=4294967295 ses=4294967295 subj=system_u:system_r:initrc_t:s0 op=add_rule key="auoms" list=4 res=1
=====================

Is there any way we can reduce all this logging?

Thanks.

**Comment by jayaich** [comment]
Any ideas what we can do about this?
We have also noticed that the syslog file is being written to every second as well. so that is huge. 
We tried to stop and disable the 'auoms' service, but a few minutes later something else automatically re-enabled it and restarted it.
We have no idea what rules it is expecting, and as far as we can tell the auoms rules are loaded.

**Comment by taglines** [comment]
The "Found desired audit rules not currently loaded, loading new rules" messages are due to a bug in the rules diff code thjat was fixed in commit [b875dfaddaa3cf5e6673f8c25057ea9253e343ba](https://github.com/microsoft/OMS-Auditd-Plugin/commit/b875dfaddaa3cf5e6673f8c25057ea9253e343ba).

The extra audit log volume is not due to auoms itself, but probably due to the "-a exit,always -S execve" rules added by the ASC/OMS agent. You can see the rules added by the omsgant by looking in /etc/opt/microsoft/auoms/rules.d/oms-security-audit.rules.
