### ISSUE TITLE
Unnecessary use of system()

### ISSUE THREAD

**Issue by jobooth** [microsoft/OMS-Auditd-Plugin#34]
https://github.com/microsoft/OMS-Auditd-Plugin/blob/f5c15acbf1373482a4d9d1bbf09ae7ee98a2f481/TempDir.cpp#L45

With the well known issues of shelling out with system() calls and given we're already compiling as C++17, it might be a good idea to change calls to system("rm -rf " ...) to use the new std::experimental::filesystem::remove_all().

**Comment by taglines** [comment]
It's only used in a unit test and we wish to avoid using experimental features.
