### ISSUE TITLE
insserv: Script auoms is broken: incomplete LSB comment.

### ISSUE THREAD

**Issue by iharrington** [microsoft/OMS-Auditd-Plugin#39]
While working on my AKS node host OS I came across a bunch of these errors.

It appears that the init script does not have all the required comments and is complaining about it. I was able to "fix it" by adding a couple lines to the comments section and restarting the service.

https://github.com/microsoft/OMS-Auditd-Plugin/blob/master/installer/auoms.init

^ in this file if you could (starting @line 8) change to 
`### BEGIN INIT INFO`
`# Provides:             auoms`
`# Required-Start:`
`# Required-Stop:`
`# Default-Start:        2 3 4 5`
`# Default-Stop:`
`# Short-Description:    OMS audit data collection daemon`
`### END INIT INFO`

should fix this.

Thanks!

**Comment by cool-mist** [comment]
I came across these errors while I was trying to register a new service with systemctl
The service got registered successfully but I could see these errors. 

Any ETA on the "fix" ?

**Comment by taglines** [comment]
Fixed with this PR: #62
