### ISSUE TITLE
auoms cores fill filesystem

### ISSUE THREAD

**Issue by jim-minter** [microsoft/OMS-Auditd-Plugin#59]
@taglines we're seeing lots of "RawEventReader: Message size (xxxxxx) in header is too large (> 262144), reading and discarding message contents" in our logs.

auoms then dumps core; I could well believe is fixed by #58.

However, then auoms is restarted, and this process repeats until the root filesystem is filled.  This is a really horrible failure mode.

Please can the `setrlimit` calls be removed from auoms and auomscollect so that these utilities honour the system's decision about whether core files should be collected or not?

Separately, please can we have a new auoms build in https://packages.microsoft.com/yumrepos/azurecore/ urgently?

**Comment by taglines** [comment]
Version 2.3.1 (see releases) resolves the crash bug.
This version also makes the setrilimt optional (use "-d") to enable that logic. Than you for pointing that out.
This version is scheduled to be published to https://packages.microsoft.com tomorrow.

**Comment by jim-minter** [comment]
Many thanks for the quick reply @taglines.  I don't actually see the change to make setrlimit optional, but maybe it's me.  It definitely merged?
